inject_pod_details: true #to get POD details in the env. eg. SN_AKS_POD_NAME
ingress_flag: true # Set True if ingress needs to be enabled and then provide valid information for ingress based on env selected
pvc_flag: false # Set True if pvc needs to be enabled and configure valid info for pvc
secrets_flag: true # Set True if secrets needs to be enabled and configure valid info for secrets
config_map_flag: false #Set True if configmap needs to be enabled and configure valid info for configMap
env_vars_flag: true # Set True if env_vars needs to be enabled and configure valid info for env_vars
service_flag: true

instrumentation:
  argument: "1" # sampler argument and value can be between 0 to 1 in string format e.g "0.25" or "1"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 500m
    memory: 2000Mi
  limits:
    cpu: 4000m
    memory: 4000Mi

image:
  repository: dtservices-repo/clm-lcc-lr-service

replicaCount: 4
env_vars:
  - name: OTEL_SERVICE_NAME
    value: clm-lcc-lr-service-deployment
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: https://ingest.lightstep.com:443
  - name: JAVA_TOOL_OPTIONS
    value: -javaagent:/opt/opentelemetry-javaagent.jar -Dotel.instrumentation.logback-mdc.add-baggage=true
  - name: OTEL_METRICS_EXPORTER
    value: otlp
  - name: OTEL_LOGS_EXPORTER
    value: none # To stop sending logs to lightstep. default is otlp.
  - name: OTEL_TRACES_SAMPLER
    value: always_on
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: k8s.container.name=clm-lcc-lr-service,k8s.namespace.name=$(SN_AKS_POD_NAMESPACE),k8s.node.name=$(SN_AKS_NODE_NAME),k8s.pod.name=$(SN_AKS_POD_NAME),service.version=$(SN_AKS_IMAGE_VERSION),k8s.deployment.name=clm-lcc-lr-service-deployment

  # Application
  - name: APP_NAME
    value: clm-lcc-lr-service
  - name: APP_PORT
    value: 8080
  - name: APP_USERNAME
    value: clmuser

  - name: ENVIRONMENT
    value: dev
  - name: APP_UPLOAD_PUBLISH_MAX_FAILURES
    value: 2
  - name: APP_HEADER_UPDATE_MAX_FAILURES
    value: 2
  # Tasks
  - name: EXECUTOR_NAME_PREFIX
    value: cpq-pool-
  - name: EXECUTOR_CORE_POOL_SIZE
    value: 16
  - name: EXECUTOR_MAX_POOL_SIZE
    value: 20
  # Kafka
  - name: KAFKA_BROKER1
    value: uswdlkafkabr01.corp.service-now.com
  - name: KAFKA_BROKER2
    value: uswdlkafkabr02.corp.service-now.com
  - name: KAFKA_BROKER3
    value: uswdlkafkabr03.corp.service-now.com
  - name: KAFKA_PORT
    value: 9094
  - name: KAFKA_USERNAME
    value: svc_kafka_dtsrvs_sp
  - name: KAFKA_TRUSTSTORE_LOCATION
    value: file:/app/cpqconsumer.jks
  - name: KAFKA_LIFECYCLE_MONITOR_INITIAL_DELAY
    value: 2000
  - name: KAFKA_LIFECYCLE_MONITOR_INTERVAL
    value: 300000
  - name: SECURITY_PROTOCOL
    value: SASL_SSL
  - name: SASL_MECHANISM
    value: PLAIN
  - name: SASL_CONFIG
    value: org.apache.kafka.common.security.plain.PlainLoginModule
      required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
  - name: TRUSTSTORE_LOCATION
    value: file:/app/cpqconsumer.jks
  - name: KEYSTORE_PATH
    value: ../../../../../keystore/truststore.p12
    # classpath:/cpqconsumer.jks
  # CPQ Topic and Consumers
  # QUOTES
  - name: CLM_QUOTE_TOPIC
    value: dev4-clm-agreementstatus-lcc
  - name: DEFAULT_RETRY_INTERVAL
    value: 2000
  - name: DEFAULT_RETRY_ATTEMPTS
    value: 3
  - name: DEFAULT_RETRY_LISTENER_INTERVAL
    value: 10000
  - name: RETRY_TYPE
    value: fixed
  - name: RETRY_INTERVAL
    value: 100
  - name: RETRY_ATTEMPTS
    value: 3

  #Feign Clients
  - name: LCC_CLIENT_URL
    value: https://surfsedev.service-now.com
  - name: LCC_CLIENT_USERNAME
    value: api.integrations_subprod
  - name: LCC_CLIENT_ID
    value: 381f36d95e5e6e804795122e39b379f6
  - name: CONNECTION_TIMEOUT
    value: 5000
  - name: READ_TIMEOUT
    value: 30000
  - name: PING_INTERVAL_MILLIS
    value: 60000
  - name: KEEP_ALIVE_MILLIS
    value: 60000
  - name: MAX_IDLE_CONNECTIONS
    value: 40
  - name: CPQ_AUTH_CLIENT_READ_TIMEOUT
    value: 5000
  - name: CLM_AUTH_CLIENT_READ_TIMEOUT
    value: 5000
  - name: CPQ_CLIENT_READ_TIMEOUT
    value: 20000
  - name: HTTP_CLIENT_ENABLED
    value: false
  - name: OK_HTTP_ENABLED
    value: true
  - name: MICROMETER_ENABLED
    value: true
  # Spring context path
  - name: SPRING_CONTEXT_PATH
    value: /clm-lcc-legalrequest
  - name: SPRING_ENDPINT_EXPOSURES
    value: health, metrics
  - name: SPRING_ENDPOINT_HEALTH
    value: always

  # Integ Client
  - name: INTEG_URL
    value: https://integuat.service-now.com
  - name: INTEG_CLIENT_ID
    value: 7d645c58c0558450b83b41b63bc4fd8a
  - name: INTEG_USERNAME
    value: api.integrations_subprod
  #CLMThreadSleep
  - name: CLM_SLEEP_TIME
    value: 2000

  # CLM QUOTE
  - name: CLM_CONSUMER_ID
    value: clm-agreement-consumer
  - name: CLM_CONSUMER_GROUP_ID
    value: dev4-clm-agreementstatus-lcc-group
  - name: CLM_AUTO_START
    value: true
  - name: CLM_AGREEMENT_CONSUMER_GROUP_CONCURRENCY
    value: 1

  #Retry
  - name: CLM_CONSUMER_RETRY_ID
    value: clm-agreement-retry-consumer
  - name: CLM_CONSUMER_RETRY_TOPIC_NAME
    value: dev4-clm-agreementstatus-lcc-retry
  - name: CLM_CONSUMER_DLT_TOPIC_NAME
    value: dev4-clm-agreementstatus-lcc-dlt
  - name: CLM_AGREEMENTSTATUS_RETRY_GROUPID
    value: dev4-clm-agreementstatus-lcc-retry-group
  - name: CLM_CONSUMER_RETRY_AUTOSTART
    value: false
  - name: CLM_CONSUMER_RETRY_INTERVAL
    value: 60000
  - name: CLM_CONSUMER_RETRY_CONCURRENCY
    value: 1
  - name: CLM_CONSUMER_MAX_RETRIES
    value: 1
  - name: CLM_CONSUMER_MAX_POLL_INTERVAL
    value: 900000

env_vars_from_secret:
  - name: APP_PASSWORD
    value: dtservices_clm_agreement_services_dev_auth_app_password
  # Kafka
  - name: KAFKA_PASSWORD
    value: dtservices_clm_agreement_services_dev_kafka_sasl_pwd_new
  - name: TRUSTSTORE_PASSWORD
    value: dtservices_clm_agreement_services_dev_auth_truststore_password
  - name: LCC_CLIENT_PASSWORD
    value: dtservices_clm_agreement_services_dev_auth_surf_password
  - name: LCC_CLIENT_SECRET
    value: dtservices_clm_agreement_services_dev_auth_surf_client_secret

  #LightStep
  - name: OTEL_EXPORTER_OTLP_HEADERS
    value: dtservices_clm_agreement_services_dev_lightstep_token

  #Integ
  - name: INTEG_PASSWORD
    value: dtservices_clm_agreement_services_uat_integ_password
  - name: INTEG_CLIENT_SECRET
    value: dtservices_clm_agreement_services_uat_integ_client_secret

secrets:
  obj:
    - objectname: dtservices_clm_agreement_services_dev_auth_app_password
      value_type: password
    - objectname: dtservices_clm_agreement_services_dev_kafka_sasl_pwd_new
      value_type: password
    - objectname: dtservices_clm_agreement_services_dev_auth_truststore_password
      value_type: password
    - objectname: dtservices_clm_agreement_services_dev_auth_surf_password
      value_type: password
    - objectname: dtservices_clm_agreement_services_dev_auth_surf_client_secret
      value_type: password
    - objectname: dtservices_clm_agreement_services_dev_lightstep_token
      value_type: password
    - objectname: dtservices_clm_agreement_services_uat_integ_password
      value_type: password
    - objectname: dtservices_clm_agreement_services_uat_integ_client_secret
      value_type: password


technical_owner : praveen.dyavanapally
department: IT
costcenter: cc-5400
business_owner: thangavel.viswam
select_env : dev
envtype: DEV
